apiVersion: cloudresources.appvia.io/v2beta2
kind: CloudResourceKind
metadata:
  name: azurerm-resource-group
spec:
  description: Azure Resource Group resource kind
  version: "1.0.0"
  provider: terraform
  cloud: azure
  terraform:
    search:
      template: |
        # List Resource Groups by tags (if provided)
        data "azurerm_resources" "rgs" {
          type = "Microsoft.Resources/resourceGroups"

          required_tags = var.resource_tags
        }

        output "output" {
          value = [for r in data.azurerm_resources.rgs.resources : {
            name = r.name
          }]
        }

    resource:
      template: |
        # Expect identifier: name
        data "azurerm_resource_group" "result" {
          name = var.name
        }

        output "id" {
          value = data.azurerm_resource_group.result.id
        }

        output "name" {
          value = data.azurerm_resource_group.result.name
        }

        output "location" {
          value = data.azurerm_resource_group.result.location
        }

        output "tags" {
          value = data.azurerm_resource_group.result.tags
        }


